site_name: ImportSpy
site_url: https://importspy.github.io/importspy/
repo_url: https://github.com/importspy/importspy
repo_name: importspy/importspy

theme:
  name: material
  logo: assets/importspy-logo.png
  palette:
    - scheme: default
      primary: purple
      accent: light blue
  features:
    - navigation.tabs
    - navigation.instant

nav:
  - Home: index.md
  - Introduction:
      - What is ImportSpy: intro/overview.md
      - Installation: intro/install.md
      - Quickstart: intro/quickstart.md
  - Operating Modes:
      - Embedded Mode: modes/embedded.md
      - CLI Mode: modes/cli.md
  - YAML Contracts:
      - Syntax: contracts/syntax.md
      - Examples: contracts/examples.md
  - Advanced Usage:
      - CI/CD Integration: advanced/cicd.md
      - Plugin Systems: advanced/plugins.md
      - SpyModel Architecture: advanced/spymodel.md
      - Violation System: advanced/violations.md
  - Validation & Errors: validation-errors.md
  - API Reference: api-reference.md
  - Contributing: contribute.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

markdown_extensions:
  - pymdownx.snippets
  - admonition
  - pymdownx.tabbed:
      alternate_style: true


